global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['host.docker.internal:9091']

  - job_name: 'jupyter_metrics'
    static_configs:
      - targets: ['host.docker.internal:8000']

